language: php

php:
  - 7.0
  - 7.1
  - 7.2.0

before_script:
  - composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
  - composer install --dev

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml --configuration phpunit.xml

after_script:
  - travis_retry php vendor/bin/php-coveralls -v
