language: php

php:
  - 7.0
  - 7.1
  - 7.2.0

before_script:
  - composer install --no-interaction

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - travis_retry php vendor/bin/php-coveralls -v
